main:
  method: 'get'
  path: ~
  controller: App\Controller\Home\HomeController
  action: index
movie:
  method: 'get'
  path: movie
  controller: App\Controller\Movie\MovieController
  action: index
